### PR TITLE
fix(device): add check for created partition

### LINKED ISSUE #20: Runtime Panic Within Node Plugin
We observed a go runtime panic within device local node plugin. Just putting out here to see if anyone can take look into it.

```
2021-06-07T16:57:10.817343241+05:30 stderr F I0607 16:57:10.817191       1 device-util.go:170] GetPart Error, {DiskName:sda Size:10737418240}
2021-06-07T16:57:10.91741737+05:30 stderr F I0607 16:57:10.917210       1 device-util.go:288] Disk: DiskName not correct
2021-06-07T16:57:10.917434131+05:30 stderr F I0607 16:57:10.917232       1 device-util.go:170] GetPart Error, {DiskName:sda Size:10737418240}
2021-06-07T16:57:13.019507828+05:30 stderr F I0607 16:57:13.019321       1 device-util.go:288] Disk: DiskName not correct
2021-06-07T16:57:13.019534179+05:30 stderr F I0607 16:57:13.019352       1 device-util.go:170] GetPart Error, {DiskName:sdd Size:3189013217280}
2021-06-07T16:57:13.019604142+05:30 stderr F I0607 16:57:13.019531       1 device-util.go:288] Disk: DiskName not correct
2021-06-07T16:57:13.019619593+05:30 stderr F I0607 16:57:13.019555       1 device-util.go:170] GetPart Error, {DiskName:sdd Size:3189013217280}
2021-06-07T16:57:13.618848367+05:30 stderr F I0607 16:57:13.618659       1 device-util.go:288] Disk: DiskName not correct
2021-06-07T16:57:13.618869735+05:30 stderr F I0607 16:57:13.618686       1 device-util.go:170] GetPart Error, {DiskName:sde Size:12000136527872}
2021-06-07T16:57:13.618873316+05:30 stderr F I0607 16:57:13.618697       1 device-util.go:107] Running WipeFS for Partition sdb 2
2021-06-07T16:57:13.919818946+05:30 stderr F I0607 16:57:13.919580       1 device-util.go:288] Disk: DiskName not correct
2021-06-07T16:57:13.919837104+05:30 stderr F I0607 16:57:13.919603       1 device-util.go:170] GetPart Error, {DiskName:sde Size:12000136527872}
2021-06-07T16:57:13.919840384+05:30 stderr F E0607 16:57:13.919664       1 runtime.go:73] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
2021-06-07T16:57:13.919843152+05:30 stderr F goroutine 103 [running]:
2021-06-07T16:57:13.919845434+05:30 stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14b5ca0, 0xc000393a80)
2021-06-07T16:57:13.91985613+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
2021-06-07T16:57:13.919858808+05:30 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2021-06-07T16:57:13.919861079+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x89
2021-06-07T16:57:13.919863579+05:30 stderr F panic(0x14b5ca0, 0xc000393a80)
2021-06-07T16:57:13.919865765+05:30 stderr F 	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
2021-06-07T16:57:13.919868366+05:30 stderr F github.com/openebs/device-localpv/pkg/device.wipefsAndCreatePart(0xc000cc8cd5, 0x3, 0x2, 0xc0004ac2a4, 0x24, 0x8a4000, 0xc000d085e0, 0xa, 0x0, 0x1)
2021-06-07T16:57:13.919870885+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/device/device-util.go:107 +0x72f
2021-06-07T16:57:13.919873027+05:30 stderr F github.com/openebs/device-localpv/pkg/device.CreateVolume(0xc00073e780, 0x1, 0xc00073e780)
2021-06-07T16:57:13.91987519+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/device/device-util.go:89 +0x3fd
2021-06-07T16:57:13.919877345+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).syncVol(0xc00048cae0, 0xc00073e780, 0x0, 0x0)
2021-06-07T16:57:13.919879533+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:91 +0x4b
2021-06-07T16:57:13.919882012+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).syncHandler(0xc00048cae0, 0xc0005a2340, 0x37, 0xc00083ddb0, 0x11e8954)
2021-06-07T16:57:13.919884183+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:57 +0x13d
2021-06-07T16:57:13.919886428+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).processNextWorkItem.func1(0xc00048cae0, 0x1362b20, 0xc0006ea560, 0x0, 0x0)
2021-06-07T16:57:13.919888691+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:230 +0xd7
2021-06-07T16:57:13.91989105+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).processNextWorkItem(0xc00048cae0, 0x1)
2021-06-07T16:57:13.919893251+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:240 +0x4d
2021-06-07T16:57:13.91989537+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).runWorker(0xc00048cae0)
2021-06-07T16:57:13.919897546+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:191 +0x2b
2021-06-07T16:57:13.91989968+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a24f0)
2021-06-07T16:57:13.919901849+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
2021-06-07T16:57:13.919903992+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a24f0, 0x3b9aca00, 0x0, 0x1, 0xc00011c780)
2021-06-07T16:57:13.919906101+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
2021-06-07T16:57:13.91990823+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0006a24f0, 0x3b9aca00, 0xc00011c780)
2021-06-07T16:57:13.9199107+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2021-06-07T16:57:13.919912858+05:30 stderr F created by github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).Run
2021-06-07T16:57:13.919914971+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:177 +0x265
2021-06-07T16:57:13.921975666+05:30 stderr F panic: runtime error: index out of range [0] with length 0 [recovered]
2021-06-07T16:57:13.921990187+05:30 stderr F 	panic: runtime error: index out of range [0] with length 0
2021-06-07T16:57:13.922018166+05:30 stderr F 
2021-06-07T16:57:13.922022345+05:30 stderr F goroutine 103 [running]:
2021-06-07T16:57:13.922025998+05:30 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2021-06-07T16:57:13.922030533+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x10c
2021-06-07T16:57:13.922035537+05:30 stderr F panic(0x14b5ca0, 0xc000393a80)
2021-06-07T16:57:13.922039044+05:30 stderr F 	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
2021-06-07T16:57:13.922046513+05:30 stderr F github.com/openebs/device-localpv/pkg/device.wipefsAndCreatePart(0xc000cc8cd5, 0x3, 0x2, 0xc0004ac2a4, 0x24, 0x8a4000, 0xc000d085e0, 0xa, 0x0, 0x1)
2021-06-07T16:57:13.922050847+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/device/device-util.go:107 +0x72f
2021-06-07T16:57:13.922054326+05:30 stderr F github.com/openebs/device-localpv/pkg/device.CreateVolume(0xc00073e780, 0x1, 0xc00073e780)
2021-06-07T16:57:13.922057886+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/device/device-util.go:89 +0x3fd
2021-06-07T16:57:13.922264779+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).syncVol(0xc00048cae0, 0xc00073e780, 0x0, 0x0)
2021-06-07T16:57:13.922272982+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:91 +0x4b
2021-06-07T16:57:13.922278953+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).syncHandler(0xc00048cae0, 0xc0005a2340, 0x37, 0xc00083ddb0, 0x11e8954)
2021-06-07T16:57:13.922283195+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:57 +0x13d
2021-06-07T16:57:13.922287216+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).processNextWorkItem.func1(0xc00048cae0, 0x1362b20, 0xc0006ea560, 0x0, 0x0)
2021-06-07T16:57:13.922291221+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:230 +0xd7
2021-06-07T16:57:13.922295171+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).processNextWorkItem(0xc00048cae0, 0x1)
2021-06-07T16:57:13.922299196+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:240 +0x4d
2021-06-07T16:57:13.922303001+05:30 stderr F github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).runWorker(0xc00048cae0)
2021-06-07T16:57:13.92230684+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:191 +0x2b
2021-06-07T16:57:13.922310849+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a24f0)
2021-06-07T16:57:13.922314835+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
2021-06-07T16:57:13.922318811+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a24f0, 0x3b9aca00, 0x0, 0x1, 0xc00011c780)
2021-06-07T16:57:13.922322745+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
2021-06-07T16:57:13.922326806+05:30 stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0006a24f0, 0x3b9aca00, 0xc00011c780)
2021-06-07T16:57:13.922330838+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2021-06-07T16:57:13.92233473+05:30 stderr F created by github.com/openebs/device-localpv/pkg/mgmt/volume.(*VolController).Run
2021-06-07T16:57:13.922338818+05:30 stderr F 	/Users/praveen.gt/go/src/github.com/openebs/device-localpv/pkg/mgmt/volume/volume.go:177 +0x265
```

### PR DESCRIPTION
**Pull request by akhilerm**
- add additional check for the created partition before performing wipefs

Fix in part: https://github.com/openebs/device-localpv/issues/20

Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

### CODE REVIEW

File: pkg/device/device-util.go [hunk 1]
```diff
@@ -121,6 +121,10 @@ func wipefsAndCreatePart(disk string, start uint64, partitionName string, size u
 		return err
 	}
 
+	if len(pList) == 0 {
+		return fmt.Errorf("could not find created partition %s", partitionName)
```
Comment (praveengt) [inline pkg/device/device-util.go:125]: return value of fmt.Errorf will be nil, we need to return error

Comment (akhilerm) [reply pkg/device/device-util.go:125]: Nope. It returns error. Ref. https://golang.org/pkg/fmt/#Errorf

**Review by pawanpraka1 — APPROVED** [review]
looks good.
