### PR TITLE
fix(provisioning): remove Gi unit conversion for pv capacity

### LINKED ISSUE #38: volume creation fails even after having enough capacity on node
Even we have enough capacity on node (correctly published under csi storage capacity resource), pvc creation is failing with following error - 
```
2021-08-26T01:25:12.850848431+05:30 stderr F E0826 01:25:12.850660       1 device-util.go:161] findBestPart Failed
2021-08-26T01:25:12.850852115+05:30 stderr F E0826 01:25:12.850687       1 volume.go:243] error syncing 'openebs-device/pvc-9c9d05b5-3dc1-4201-84bb-6f416532e508': free space of 9060352MiB not found on disk name: xxxx-*, requeuing
```
Capacity asked by PVC - 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    device.csi.openebs.io/csi-volume-name: pvc-9c9d05b5-3dc1-4201-84bb-6f416532e508
    volume.beta.kubernetes.io/storage-provisioner: device.csi.openebs.io
    volume.kubernetes.io/selected-node: node-xyz
  creationTimestamp: "2021-08-25T18:56:08Z"
  name: ...
  namespace: ...
  resourceVersion: "105909663"
  uid: 9c9d05b5-3dc1-4201-84bb-6f416532e508
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9500G
  storageClassName: hdd-xxxx-part-ext4-0
  volumeMode: Filesystem
status:
  phase: Pending
```
Relevant CSI storage capacity resource -
```
apiVersion: storage.k8s.io/v1alpha1
capacity: 9060351Mi
kind: CSIStorageCapacity
...
```

Issue is happening due to conversion of pv size to nearest Gi unit [here](https://github.com/openebs/device-localpv/blob/develop/pkg/driver/controller.go#L99-L112). Any specific reason of doing so? Can we remove the Gi unit conversion?

### PR DESCRIPTION
**Pull request by iyashu**
Kept the volume capacity as multiple of mebibyte for block alignment that [we have at node agent](https://github.com/openebs/device-localpv/blob/91f34ce52fc6ae3696c84a08cf98e9e2f7378b04/pkg/device/device-util.go#L291).

Fixes #38

### CODE REVIEW

File: pkg/driver/controller.go [hunk 1]
```diff
@@ -569,6 +559,8 @@ func (cs *controller) GetCapacity(
 		}
 	}
 
+	// round off the available capacity to nearest Mi
+	availableCapacity = (availableCapacity / Mi) * Mi
```
Comment (pawanpraka1) [inline pkg/driver/controller.go:563]: we should ceil to the nearest Mi.

Comment (iyashu) [reply pkg/driver/controller.go:563]: nope, this is available capacity eventually to be used by kube-scheduler. Making it ceil will give false indication about allocatable capacity available on node.

Comment (pawanpraka1) [reply pkg/driver/controller.go:563]: hmmm, let us put a comment about why we are doing a floor here.

**Review by pawanpraka1 — APPROVED** [review]
looks good. one minor comment.

File: pkg/driver/controller.go (hunk 1 above)
Comment (iyashu) [reply pkg/driver/controller.go:563]: Sure, done!
